version: '3.8'

name: domaci2

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ljmatovic/domaci2-backend
    container_name: domaci2-backend
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=mydatabase
      - DB_PORT=3306
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: always